# Generated by Django 5.0.3 on 2024-04-10 00:51

import django.db.models.deletion
import main.models.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', main.models.file.FileField(unique=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='main.file'),
            preserve_default=False,
        ),
    ]
